title: Contracts
theme: jekyll-theme-minimal
plugins:
#  - jekyll-feed
#  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-paginate 

social:
  name: Jon Loucks
  links:
    - https://github.com/jonloucks
    - https://linkedin.com/in/jon-loucks-b94a19346

include:
  - LICENSE.md
  - CONTRIBUTING.md 
  - CODE_OF_CONDUCT.md
  - CODING_STANDARDS.md
  - PULL_REQUEST_TEMPLATE.md
  - SECURITY.md
  - STYLE_GUIDE.md


