[versions]
junit-version = "5.14.3"
mockito-version = "[5.0,6.0)"
gradle-kit-version = "[1.2.0,2.0.0)"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-version"}
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-version"}
