name: Main Pull Request Matrix

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: main-pull-request-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: # maximum of 25 combinations
        distribution: [ 'zulu', 'temurin' ]
        java-jdk-version: [ 17, 25 ] # oldest and latest LTS JDK
        java-compiler-version: [ 17 ] # vector, only minimum JDK
        java-source-version: [ 9, 11 ] # current source version and next version
    permissions:
      contents: read
      packages: read
      pages: read

    steps:
    - name: Assigning SIMPLE_REPOSITORY_NAME
      run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Assigning SIMPLE_BRANCH_NAME
      run: |
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
        SIMPLE_BRANCH_NAME="${BRANCH_NAME//\//-}"
        echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV

    - name: Checkout Main Project
      uses: actions/checkout@v4
      with:
        path: main-project

    - name: Set up JDK ${{ matrix.java-jdk-version }} with ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-jdk-version }}
        java-package: 'jdk'
        distribution: ${{ matrix.distribution }}
        settings-path: ${{ github.workspace }}

    - name: Set up Gradle environment
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle with java source ${{ matrix.java-source-version }}
      working-directory: main-project
      run: ./gradlew check jacocoTestReport jacocoTestCoverageVerification spotbugsMain
      env:
        PROJECT_WORKFLOW: 'main-pull-request-matrix'
        KIT_JAVA_COMPILER_VERSION: ${{ matrix.java-compiler-version }}
        KIT_JAVA_SOURCE_VERSION: ${{ matrix.java-source-version }}

    - name: Upload Smoke Test
      uses: actions/upload-artifact@v4
      with:
        name: smoke-app
        path: |
          "${{ env.SIMPLE_REPOSITORY_NAME }}-smoke/build/distributions/*.tar"

  smoke-test:
    name: main-pull-request-matrix-smoke
    runs-on: ubuntu-latest
    strategy:
      matrix: # maximum of 25 combinations
        distribution: [ 'zulu', 'temurin' ]
        java-jre-version: [ 11 ] # , 17, 21, 25 ]  # all LTS JRE's
    permissions:
      contents: read
      packages: read
      pages: read

    steps:
      - name: Assigning SIMPLE_REPOSITORY_NAME
        run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Download Smoke Test
        uses: actions/download-artifact@v4
        with:
          name: smoke-app

      - name: Set up JRE ${{ matrix.java-jre-version }} for Running
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-jre-version }}
          java-package: 'jre'
          distribution: ${{ matrix.distribution }}

      #
      #    - name: Assigning JRE_HOME
      #      run: |
      #        JRE_ENV_VARIABLE="${JAVA_HOME_${{ matrix.java-jre-version }}_X64}"
      #        echo "JRE_HOME=${JRE_ENV_VARIABLE}" >> $GITHUB_ENV


      - name: Run Smoke Tests
        run: |
          if [ -d "bin/" ]; then
            ./bin/smoke
          fi