name: Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix: # row matrix only!
        java-version: [ 17 ]
        distribution: [ 'temurin' ]
        java-compiler-version: [ 17 ]
        java-source-version: [ 9 ]
    permissions:
      contents: write
      packages: write
      pages: write

    steps:
    - name: Modify branch name
      run: |
        BRANCH_NAME="${{ github.head_ref || github.ref_name}}"
        # Replace slashes with underscores
        MODIFIED_BRANCH_NAME_SLASHS_REPLACED="${BRANCH_NAME//\//_}"
        # Remove dashes
        SIMPLE_BRANCH_NAME="${MODIFIED_BRANCH_NAME_SLASHS_REPLACED//-/}"
        echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV
    - name: Checkout badges branch dedicated to storing badges only
      uses: actions/checkout@v4
      with:
        ref: badges
        path: badges

    - name: Checkout Main Project
      uses: actions/checkout@v4
      with:
        path: main-project

    - name: Set up Java ${{ matrix.java-version }} with ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle with java source ${{ matrix.java-source-version }}
      working-directory: main-project
      run: ./gradlew build jacocoTestReport
      env:
        PROJECT_WORKFLOW: 'main-pull-request'
        KIT_JAVA_COMPILER_VERSION: ${{ matrix.java-compiler-version }}
        KIT_JAVA_SOURCE_VERSION: ${{ matrix.java-source-version }}

    - name: Upload JaCoCo report artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: main-project/build/reports/jacoco/test/html/

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.11.0
      with:
        coverage-badge-filename: ${{ env.SIMPLE_BRANCH_NAME }}-coverage.svg
        badges-directory: badges
        jacoco-csv-file: main-project/build/reports/jacoco/test/jacocoTestReport.csv

    - name: Commit and Push the Badge
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update JaCoCo coverage badge'
        add: '*.svg'
        pull: '--rebase --autostash'
        cwd: badges

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"

    - name: Test Coverage Verification
      working-directory: main-project
      run: ./gradlew jacocoTestCoverageVerification
      env:
        PROJECT_WORKFLOW: 'main-pull-request'
        KIT_JAVA_COMPILER_VERSION: ${{ matrix.java-compiler-version }}
        KIT_JAVA_SOURCE_VERSION: ${{ matrix.java-source-version }}