name: Main Pull Request Matrix

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: main-pull-request-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: # maximum of 25 combinations
        java-jdk-version: [ 17, 21, 25 ]
        distribution: [ 'zulu', 'temurin' ]
        java-compiler-version: [ 17 ] # vector, only minimum JDK
        java-source-version: [ 9, 11 ] # highest is minimum LTS
        java-jre-version: [ 11 ] # 17, 21, 25
    permissions:
      contents: read
      packages: read
      pages: read

    steps:
    - name: Assigning SIMPLE_REPOSITORY_NAME
      run: echo "SIMPLE_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Assigning SIMPLE_BRANCH_NAME
      run: |
        BRANCH_NAME="${{ github.head_ref || github.ref_name}}"
        SIMPLE_BRANCH_NAME="${BRANCH_NAME//\//-}"
        echo "SIMPLE_BRANCH_NAME=${SIMPLE_BRANCH_NAME}" >> $GITHUB_ENV

    - name: Checkout Main Project
      uses: actions/checkout@v4
      with:
        path: main-project

    - name: Set up JRE ${{ matrix.java-jre-version }} for Running
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-jre-version }}
        java-package: 'jre'
        distribution: ${{ matrix.distribution }}

    - name: Set up JDK ${{ matrix.java-jdk-version }} with ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-jdk-version }}
        distribution: ${{ matrix.distribution }}
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Gradle environment
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle with java source ${{ matrix.java-source-version }}
      working-directory: main-project
      run: ./gradlew check jacocoTestReport jacocoTestCoverageVerification spotbugsMain
      env:
        PROJECT_WORKFLOW: 'main-pull-request-matrix'
        KIT_JAVA_COMPILER_VERSION: ${{ matrix.java-compiler-version }}
        KIT_JAVA_SOURCE_VERSION: ${{ matrix.java-source-version }}

    - name: Run Smoke Tests
      working-directory: main-project
      run: |
        if [ -d "${SIMPLE_REPOSITORY_NAME}-smoke/build/install/smoke" ]; then
          cd "${SIMPLE_REPOSITORY_NAME}-smoke/build/install/smoke"
          JAVA_HOME=${{ env.JAVA_HOME_11_X64 }} ./bin/smoke
        fi

